### 21.05.31 서현진 한경아카데미

### 1. 넘파이를 사용하여 다음과 같은 행렬을 만드시오.

In [2]:
import numpy as np

In [6]:
a = (np.arange(1, 9).reshape(2,4) ) * 10 ; a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

### 2. 다음 행렬과 같은 행렬이 있다.
m = np.array([[ 0, 1, 2, 3, 4],
 [ 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14]])
 
#### 1) 이 행렬에서 값 7을 인덱싱한다.

#### 2) 이 행렬에서 값 14을 인덱싱한다.

#### 3) 이 행렬에서 배열 [ 6,7]을 슬라이싱한다.

#### 4) 이 행렬에서 배열 [7,12]을 슬라이싱한다.

#### 5) 이 행렬에서 배열 [[3,4], [8,9]]을 슬라이싱한다.


In [8]:
m = np.array([[ 0, 1, 2, 3, 4], [ 5, 6, 7, 8, 9], [10, 11, 12, 13, 14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
# 1 )
m[1,2]  # m[1][2]

7

In [11]:
# 2 )
m[2,4] # m[-1,-1] 

14

In [13]:
# 3 )
m[1, 1:3]

array([6, 7])

In [15]:
# 4 )
m[1:3, 2] # m[1:, 2]

array([ 7, 12])

In [19]:
# 5 )
m[:2, 3:5]  # m[:2, 3:]

array([[3, 4],
       [8, 9]])

### 3. 2번의 행렬 m을 1차원 벡터 f 로 변환한 후 다음의 문제를 푸시오.
1) 이 배열에서 3의 배수를 찾아라.

2) 이 배열에서 4로 나누면 1이 남는 수를 찾아라.

3) 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.

In [21]:
f = m.flatten(); f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [39]:
# 1)
ex1 = f[ np.logical_and(f%3 == 0, f !=0 ) ] ; ex1

array([ 3,  6,  9, 12])

In [41]:
# 2)
ex2 = f[ f%4 == 1 ]; ex2

array([ 1,  5,  9, 13])

In [42]:
# 3)
ex3 = ex1[ ex1%4 ==1 ] ; ex3

array([9])

### 4. 값을 직접 입력하지 말고 아래의 행렬을 만드시오

2, 1, 0, 0, 0

3, 2, 1, 0, 0

0, 3, 2, 1, 0

0, 0, 3, 2, 1

0, 0, 0, 3, 2

In [48]:
np.eye( 5, 5, 1) + np.eye( 5, 5, 0) * 2 + np.eye( 5, 5, -1) *3

array([[2., 1., 0., 0., 0.],
       [3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.],
       [0., 0., 0., 3., 2.]])

### 5. 0에서 10까지 랜덤 실수값으로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구하시오.

1) 전체의 최댓값

2) 각 행의 합

3) 각 행의 최댓값

4) 각 열의 평균

5) 각 열의 최솟값

In [4]:
np.random.seed(2021)
mtx5= np.random.uniform(0,10,30).reshape(5, 6) ; mtx5

array([[6.05978279, 7.33369361, 1.38947157, 3.12673084, 9.97243281,
        1.28162375],
       [1.78993106, 7.52925429, 6.62160514, 7.84310132, 0.96894396,
        0.58571285],
       [9.6239599 , 6.16557444, 0.86629961, 5.61272363, 6.16524709,
        9.63843023],
       [5.74304294, 3.71160848, 4.52145244, 2.01850248, 5.69305118,
        1.95095974],
       [5.83704016, 4.76313474, 5.178144  , 8.23098634, 7.32225027,
        0.69056275]])

In [5]:
# 1) 전체의 최댓값
mtx5.max()   # np.max(mtx5)

9.972432813403188

In [58]:
#2)각 행의 합
mtx5.sum(axis = 1)

array([29.16373537, 25.33854862, 38.07223489, 23.63861727, 32.02211826])

In [60]:
#3)각 행의 최댓값
mtx5.max(axis =1)

array([9.97243281, 7.84310132, 9.63843023, 5.74304294, 8.23098634])

In [61]:
#4)각 열의 평균
mtx5.mean(axis = 0)

array([5.81075137, 5.90065311, 3.71539455, 5.36640892, 6.02438506,
       2.82945787])

In [62]:
#5)각 열의 최솟값
mtx5.min(axis =0)  # np.min(mtx5, axis =0)

array([1.78993106, 3.71160848, 0.86629961, 2.01850248, 0.96894396,
       0.58571285])

### 6. 다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은 배열이다. 영어 성적을 기준으로 각 열(column)을 재정렬하시오.

In [63]:
# array([[ 1, 2, 3, 4], [ 46, 99, 100, 71], [ 81, 59, 90, 100]])

In [137]:
mtx6 = np.array([[ 1, 2, 3, 4], [ 46, 99, 100, 71], [ 81, 59, 90, 100]]) ; mtx6

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [143]:
mtx6[:, mtx6[1].argsort()]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

### - Sorting

In [10]:
# 그냥 sort 하면 각 원소들이 각각 sorting됨
score = np.array([[1,2,3,4],[46,99,100,71],[81,59,90,100]])
np.sort(score, axis=1)

array([[  1,   2,   3,   4],
       [ 46,  71,  99, 100],
       [ 59,  81,  90, 100]])

In [13]:
np.argsort(score[1])  # 오름차순

array([0, 3, 1, 2], dtype=int64)

In [15]:
np.argsort(score[1])[::-1]  # 내림차순

array([2, 1, 3, 0], dtype=int64)

In [16]:
score[:, np.argsort(score[1]) ] # argsort(기준) 오름차순

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

In [18]:
score[:, np.argsort(score[1]) [::-1]]  # argsort(기준) 내림차순

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

### 7. 주사위를 100번 던지는 가상 실험을 파이썬으로 작성하고, 던져서 나오는 숫자의 평균을 구하시오.

In [100]:
np.random.seed(2021)
mtx7= np.random.randint(1,7,100); mtx7

array([5, 6, 2, 1, 6, 5, 4, 6, 6, 6, 1, 5, 2, 6, 2, 2, 5, 6, 3, 3, 1, 4,
       2, 1, 3, 4, 5, 6, 1, 6, 2, 3, 6, 2, 6, 2, 3, 3, 5, 6, 3, 4, 2, 3,
       3, 1, 3, 5, 6, 4, 4, 2, 2, 2, 3, 6, 4, 4, 5, 4, 2, 5, 2, 2, 5, 4,
       6, 4, 4, 4, 3, 2, 4, 3, 6, 3, 3, 1, 5, 4, 2, 4, 2, 5, 3, 4, 2, 3,
       6, 3, 6, 3, 4, 5, 6, 2, 2, 6, 1, 6])

In [101]:
mtx7.mean()  #np.mean(mtx7)

3.7

### 8. 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하시오.

In [163]:
# 소수점이하 반올림
# days_ earnings_rate ~N(0,1)
days_earnings_rate = np.random.normal(0,1,250)* 0.01 ; # days_earnings_rate

# 250일간의 주가변동
price = 10000
for i in range(0, 250):
    price = price * days_earnings_rate[i] + price
    print(f'{i+1}번째 날의 주가는 {round(price)}원 입니다.')

1번째 날의 주가는 10020원 입니다.
2번째 날의 주가는 9856원 입니다.
3번째 날의 주가는 9913원 입니다.
4번째 날의 주가는 9904원 입니다.
5번째 날의 주가는 9990원 입니다.
6번째 날의 주가는 10139원 입니다.
7번째 날의 주가는 10250원 입니다.
8번째 날의 주가는 10142원 입니다.
9번째 날의 주가는 10148원 입니다.
10번째 날의 주가는 10082원 입니다.
11번째 날의 주가는 10182원 입니다.
12번째 날의 주가는 10103원 입니다.
13번째 날의 주가는 10043원 입니다.
14번째 날의 주가는 10177원 입니다.
15번째 날의 주가는 10289원 입니다.
16번째 날의 주가는 10225원 입니다.
17번째 날의 주가는 10304원 입니다.
18번째 날의 주가는 10415원 입니다.
19번째 날의 주가는 10473원 입니다.
20번째 날의 주가는 10405원 입니다.
21번째 날의 주가는 10291원 입니다.
22번째 날의 주가는 10242원 입니다.
23번째 날의 주가는 10372원 입니다.
24번째 날의 주가는 10297원 입니다.
25번째 날의 주가는 10238원 입니다.
26번째 날의 주가는 10175원 입니다.
27번째 날의 주가는 9902원 입니다.
28번째 날의 주가는 10151원 입니다.
29번째 날의 주가는 10194원 입니다.
30번째 날의 주가는 10255원 입니다.
31번째 날의 주가는 10275원 입니다.
32번째 날의 주가는 10402원 입니다.
33번째 날의 주가는 10707원 입니다.
34번째 날의 주가는 10651원 입니다.
35번째 날의 주가는 10498원 입니다.
36번째 날의 주가는 10470원 입니다.
37번째 날의 주가는 10447원 입니다.
38번째 날의 주가는 10531원 입니다.
39번째 날의 주가는 10487원 입니다.
40번째 날의 주가는 10610원 입니다.
41번째 날의 주가는 10622원 입니다.
42번째 날의 주가는 10520원 입니다.
43번째 날